---

- hosts: all
  gather_facts: yes
  remote_user: root
  pre_tasks:
    - name: "Install python"
      raw: "sudo apt-get -y install python"
  roles:
    - linux
    - cmake
    - llvm10
    - grpc
    - code
    - python
    - runtime_fs
    - time

